name: s3-sink
language: Python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: clickstream
    required: false
  - name: AWS_SECRET_ACCESS_KEY
    inputType: Secret
    description: ''
    defaultValue: s3_secret_access_key
    required: false
  - name: AWS_S3_URI
    inputType: FreeText
    description: ''
    defaultValue: s3://sneak-data/tomas-snakecheating-dev-clickstream
    required: true
  - name: AWS_ACCESS_KEY_ID
    inputType: FreeText
    defaultValue: AKIA5JJJFC76E24MEO5M
    required: false
  - name: AWS_DEFAULT_REGION
    inputType: FreeText
    defaultValue: eu-north-1
    required: false
  - name: table_name
    inputType: FreeText
    description: ''
    defaultValue: glue.tomas-snakecheating-dev-clickstream
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
