name: scoring
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: clickstream
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: score
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
