name: IcebergQuery
language: python
variables:
  - name: AZURE_STORAGE_CONNECTION_STRING
    inputType: Secret
    description: ''
    defaultValue: azure_storage_connection_str
    required: true
  - name: AZURE_STORAGE_CONTAINER_NAME
    inputType: FreeText
    description: ''
    defaultValue: iceberg
    required: true
  - name: POSTGRES_CONNECTION_STR
    inputType: Secret
    description: ''
    defaultValue: postgres_connection_str
    required: true
  - name: AZURE_STORAGE_URI
    inputType: FreeText
    description: ''
    defaultValue: abfs://iceberg@williamsf1pg.dfs.core.windows.net/tomastest/native-v5/vCar_Chassis
    required: true
  - name: NAMESPACE
    inputType: FreeText
    description: ''
    defaultValue: tomastest-v2
    required: true
  - name: password
    inputType: Secret
    description: ''
    defaultValue: dashboard_passport
    required: true
  - name: TABLE_NAME
    inputType: FreeText
    description: ''
    defaultValue: native-v5
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
