name: Iceberg Sink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: clickstream
    required: false
  - name: table_name
    inputType: FreeText
    description: ''
    defaultValue: iceberg_demo
    required: false
  - name: AWS_S3_URI
    inputType: FreeText
    description: ''
    defaultValue: s3://sneak-data/tomas-snakecheating-dev-clickstream
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-destination
