name: IcebergSink
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: clickstream
    required: false
  - name: consumer_group
    inputType: FreeText
    description: ''
    defaultValue: iceberg-sink-v3.5
    required: true
  - name: leading_edge_ms
    inputType: FreeText
    description: ''
    defaultValue: 5000
    required: true
  - name: AZURE_STORAGE_CONNECTION_STRING
    inputType: Secret
    description: ''
    defaultValue: azure_connection_str
    required: true
  - name: AZURE_STORAGE_CONTAINER_NAME
    inputType: FreeText
    description: ''
    defaultValue: iceberg
    required: true
  - name: POSTGRES_CONNECTION_STR
    inputType: Secret
    description: ''
    defaultValue: POSTGRES_CONNECTION_STR
    required: true
  - name: AZURE_STORAGE_URI
    inputType: FreeText
    description: ''
    defaultValue: abfs://iceberg@quixdatalake.blob.core.windows.net/iceberg
    required: true
  - name: NAMESPACE
    inputType: FreeText
    description: ''
    defaultValue: dev
    required: true
  - name: TABLE_NAME
    inputType: FreeText
    description: ''
    defaultValue: gametelemtry
    required: true
  - name: commit_every
    inputType: FreeText
    description: ''
    defaultValue: 1000
    required: true
  - name: commit_interval
    inputType: FreeText
    description: ''
    defaultValue: 5
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
