   # Use the official Redis image from the Docker Hub
   FROM redis:latest

   # Expose the default Redis port
   EXPOSE 6379

   # Copy the start script into the container
   COPY start-redis.sh /usr/local/bin/start-redis.sh

   # Make the script executable
   RUN chmod +x /usr/local/bin/start-redis.sh

   # Set the entrypoint to the start script
   ENTRYPOINT ["/usr/local/bin/start-redis.sh"]