# Use the official Redis image from the Docker Hub
FROM redis:latest

# Install net-tools to get ifconfig
RUN apt-get update && apt-get install -y net-tools

# Expose the default Redis port
EXPOSE 6379

# Create the start script directly in the Dockerfile
RUN echo '#!/bin/sh\n' \
         'ifconfig eth0 | grep "inet " | awk "{print \$2}"\n' \
         'redis-server\n' > /usr/local/bin/start-redis.sh

# Make the script executable
RUN chmod +x /usr/local/bin/start-redis.sh

# Set the entrypoint to the start script
ENTRYPOINT ["/usr/local/bin/start-redis.sh"]